name: test-microk8s-ubuntu

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Get all script files that have changed
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: |
            assets/scripts/**.sh
            .github/workflows/test-microk8s-ubuntu.yml
          files_ignore: assets/scripts/configure-minikube-linux.sh
          since_last_remote_commit: true

      - name: Configure MicroK8s Cluster
        if: ${{ steps.changed-files.outputs.any_modified == 'true' }}
        run: |
          ASSETS_PATH="$GITHUB_WORKSPACE/assets"
          CONFIGS_PATH="/home/runner/opt/config"
          FORCE_DB_REFRESH=true
          ENGINE_PATH="/home/runner/opt/ir-engine"
          CLUSTER_ID=test
          OPS_PATH="/home/runner/opt/ir-engine-ops"
          PASSWORD= # Github actions run in password-less sudo mode.
          ENABLE_RIPPLE_STACK=false

          mkdir -p "$CONFIGS_PATH"
          curl https://raw.githubusercontent.com/ir-engine/ir-engine-ops/master/configs/local.microk8s.template.values.yaml -o "$CONFIGS_PATH/test-engine.values.yaml"
          sed -i "s,^\([[:space:]]*hostUploadFolder:\).*,\1 '/home/runner/opt/ir-engine/packages/server/upload'," "$CONFIGS_PATH/test-engine.values.yaml"

          bash "$ASSETS_PATH/scripts/configure-microk8s-linux.sh" \
          -a "$ASSETS_PATH" \
          -c "$CONFIGS_PATH" \
          -d "$FORCE_DB_REFRESH" \
          -f "$ENGINE_PATH" \
          -i "$CLUSTER_ID" \
          -o "$OPS_PATH" \
          -p "$PASSWORD" \
          -r "$ENABLE_RIPPLE_STACK"
        shell: bash
